dataset:
  path: "/mnt/data/das-sb/dataset_hdf5_processed"
  type: "abc"
  num_point: 2048
model:
  path: "log/PointNet/2024-02-04_13-57/sinkhorn/PointNet/checkpoints/self_best_model.pth"
  name: "BYOL"
  proj_dim: 256
  tau: 0.01
  K: 64
  angle: 0.0
  md: "pn"
  crop: [0.85, 0.85]
  dims: 1024
  neighs: 20
util:
  gpu: 0
  workers: 8 
training:
  train: True
  train_val_percent: 0.85
  train_test_split: 0.95
  unsup: True
  l_type: "gl"
  is_recon: True
  normal: False
  log_dir: "PointNet"
  batch_size: 200
  epoch: 200
  learning_rate: 0.001
  lr_decay: 0.5
  lr_patience: 5
  optimizer: "AdamW"
  decay_rate: 0.0001
  aug: "jitter"
  early_stopping: True
  early_stopping_patience: 10
  cb: False
  return_embedding: True
pca:
  n_components: 50
tsne:
  n_components: 2
  

