dataset:
  path: "/mnt/data/das-sb/dataset_hdf5_processed"
  type: "abc"
  num_point: 2048
  train_val_percent: 0.85
  train_test_split: 0.95
model:
  path: "/home/das-sb/GIT/source_library/log/PointNet/2024-02-22_12-03/sinkhorn/PointNet/checkpoints/self_best_model.pth"
  name: "BYOL"
  proj_dim: 256
  tau: 0.01
  K: 64
  angle: 0.0
  md: "pn"
  crop: [0.85, 0.85]
  dims: 1024
  neighs: 20
util:
  gpu: 0
  workers: 8
training:
  train: True
  unsup: True
  l_type: "gl"
  is_recon: True
  normal: False
  log_dir: "PointNet"
  batch_size: 128
  epoch: 200
  learning_rate: 0.001
  lr_decay: 0.5
  lr_patience: 5
  optimizer: "AdamW"
  decay_rate: 0.0001
  aug: "jitter"
  early_stopping: True
  early_stopping_patience: 10
  cb: False
  return_embedding: True
pca:
  n_components: 512
pca_2:
  n_components: 154
results:
  dir_path: "/mnt/data/das-sb/results"

  

