dataset:
  path: "/mnt/data/das-sb/dataset_hdf5_processed"
  type: "abc"
  num_point: 2048
  train_test_split: 0.95
test:
  num_point: 1000
rep_objs_path: "/mnt/data/das-sb/results/all_rep_objects.npy"
training:
  train: False
  batch_size: 128
model:
  crop: [0.85,0.85]
util:
  gpu: 1
  workers: 8 